name: ci_main

on:
  push:
    branches:
      - 'main'

jobs:
  job_1:
    name: Build and publish to Docker
    runs-on: ubuntu-latest
    steps:
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 49251/web_app1.0:${{ steps.slug.outputs.sha7 }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  job_2:
    name: "deploy nomad job"
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: "Invoke lambda function"
        id: "invoke_lambda_function"
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_LAMBDA_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
          REGION: ap-south-1
          FunctionName: deploynomadjob
          Payload: '{"job": "diya-webapp", "tag": "${{ steps.slug.outputs.sha7 }}" }'     