name: HTML Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build HTML
        run: |
          # Add commands to build your HTML project
          # For example, if you're using a static site generator like Jekyll or Hugo:
          # gem install bundler
          # bundle install
          # bundle exec jekyll build
          # Or if you're manually building your HTML project:
          # npm install
          # npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Change this to the output directory of your build step

